### ISSUE TITLE
Includes are written for Windows only

### ISSUE THREAD

**Issue by tigoe** [sparkfun/SparkFun_HyperDisplay#1]
hyperdisplay.h line 26:
```
#include "util\hyperdisplay_default_conf.h" // The default configuration in case 
```
Change \ to / in order to compile for anything other than a Windows computer.

hyperdisplay.h line 35:
```
        #include "util/font5x7.h"
```

Change \ to / in order to compile for anything other than a Windows computer.

**Comment by oclyke** [comment]
Thanks @tigoe, hopefully this commit [eac2128] is satisfactory. And in case anyone else - like me - has noticed the different uses of '/' and '\\' but never really bothered to investigate here's a useful superuser StackExhcange topic on [Why does Windows use backslashes for paths and Unix forward slashes?
](https://superuser.com/questions/176388/why-does-windows-use-backslashes-for-paths-and-unix-forward-slashes)

**Comment by tigoe** [comment]
Looks like it'll do the job well, thanks!

That's fascinating about DOS, I had never thought about the fact that \ might have originated in another system, like CP/M. Thanks for digging that up!

**Comment by oclyke** [comment]
My pleasure, thanks for catching it for me! (All I have at work is a Windows machine so it takes a concerted effort to test on Mac). I'll close this issue. I must say I'm quite intrigued that you would be looking through the code... are you planning to use it? I'm in the process of upgrading it and that might break a few things, but it's a great chance for me to incorporate constructive feedback. Please let me know of any other thoughts you have!
