### ISSUE TITLE
Font/Text rendering is disabled (but does work when hardcoded) on recently added boards

### ISSUE THREAD

**Issue by antevens** [sparkfun/SparkFun_HyperDisplay#5]
### Subject of the issue
Currently font/text rendering support is restricted to platforms which have  <avr/pgmspace.h>.

### Your workbench
Arduino Nano 33 BLE Sense (nRF52840 chip)
#if __has_include ( <avr/pgmspace.h> )

### Steps to reproduce
Try rendering any text with a platform that supports text but doesn't have avr/pgmspace.h

### Expected behaviour
Fonts should be rendered, on platforms which don't support it an error should be raised.

### Actual behaviour
Compilation warning is shown but no error, no text shown on screen.

warning: #warning "HyperDisplay Default Font Not Supported. Printing will not work without a custom implementation" [-Wcpp]
             #warning "HyperDisplay Default Font Not Supported. Printing will not work without a custom implementation"
              ^~~~~~~

**Comment by oclyke** [comment]
Redirecting to #4
