### ISSUE TITLE
setCurrentWindowMemory should return int not void

### ISSUE THREAD

**Issue by antevens** [sparkfun/SparkFun_HyperDisplay#7]
### Subject of the issue
Minor compilation warning

Guessing you want to the return type to be int for success/failure rather than void?

```
 662 void hyperdisplay::setCurrentWindowMemory( color_t data, hd_pixels_t numPixels, uint8_t bpp, bool allowDynamic)
 663 {
 664         return setWindowMemory(pCurrentWindow, data, numPixels, bpp, allowDynamic);
 665 }
```

**Comment by oclyke** [comment]
This seems to be resolved by some previous commits

[HyperDisplay.h - setCurrentWindowMemory() declaration](https://github.com/sparkfun/SparkFun_HyperDisplay/blob/master/src/hyperdisplay.h#L175)
[HyperDisplay.cpp - setCurrentWindowMemory() definition](https://github.com/sparkfun/SparkFun_HyperDisplay/blob/master/src/hyperdisplay.cpp#L677-L680)
